nakahara_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  resources :todos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

nakahara_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

nakahara_app/app/models/todo.rb
class Todo < ApplicationRecord
    validates :title, presence: true
end

nakahara_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

nakahara_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :destroy]

  def index
      @todos = Todo.order(updated_at: :desc) 
      render :index
  end
  
  def new
      @todo = Todo.new
  end

  def create
      @todo = Todo.new(todo_params)

      if @todo.save
          redirect_to todos_path
      else 
          render :new
      end
  end

  def edit
      @todo = Todo.find(params[:id])
  end

  def update
      @todo = Todo.find(params[:id])
      if @todo.update(todo_params)
          redirect_to todos_path
      else 
          render :edit
      end
  end

  def destroy 
    @todo = Todo.find(params[:id])
      @todo.destroy
      redirect_to todos_path
  end

  private

  def todo_params
      params.require(:todo).permit(:title, :is_completed)
  end

  def set_todo
      @todo = Todo.find(params[:id])
  end
end

nakahara_app/app/helpers/application_helper.rb
module ApplicationHelper
end

nakahara_app/app/helpers/todos_helper.rb
module TodosHelper
end

nakahara_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NakaharaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

nakahara_app/app/views/todos/edit.html.erb
<div class="container">
  <h1>edit</h1>
  <%= form_with model: @todo, local:true do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "edit" %>
    <input type="submit" value="save">
  <% end %>
    <%= link_to 'back', todos_path, class: "back" %>
</div>

nakahara_app/app/views/todos/index.html.erb
<div class="container">
  <h1>Todo List</h1>

  <%= link_to "add_task", new_todo_path, class:"link-button"%>

  <table>
    <thead>
      <tr>
        <th>Check</th>
        <th>Task</th>
      </tr>
    </thead>
    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td style="text-align: center;">
            <%= form_tag(todo_path(todo), method: :patch) do %>
            <%= check_box_tag "todo[is_completed]", "1", todo.is_completed, id: "todo_completed_#{todo.id}" %>
            <%= label_tag "todo_completed_#{todo.id}", "" %>
            <% end%>
          </td>
          <td>
            <%= todo.title %>
          </td>
          <td>
            <%= link_to "edit", edit_todo_path(todo), class: "link-edit-button" %>
            <%= link_to "", todo_path(todo), class: "link-delete-button" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

nakahara_app/app/views/todos/new.html.erb
<div class="container">
  <h1>add_task</h1>
  <%= form_with model: @todo, local:true do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "input" %>
    <input type="submit" value="add">
  <% end %>
  <%= link_to 'back', todos_path, class: "back" %>
</div>